#
# Copyright (c) 2026
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

# Keep the sample in the standard overwrite-only MCUboot flow.
SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
