#
# Copyright (c) 2026
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_STATIC_INIT_GNU=y

CONFIG_SIDEWALK=y
CONFIG_SIDEWALK_APPLICATION_NAME="fsk-probe"
CONFIG_SIDEWALK_SUBGHZ_SUPPORT=y
CONFIG_SIDEWALK_SUBGHZ_RADIO_SX126X=y
CONFIG_SIDEWALK_SUBGHZ_TRIM_CAP_VAL=0x1212
CONFIG_SIDEWALK_LINK_MASK_FSK=y
CONFIG_SIDEWALK_DFU=n

CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_SIDEWALK_LOG_LEVEL_INF=y
CONFIG_SPI_BUS_LOG_LEVEL_WRN=y

CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_RESET_ON_FATAL_ERROR=n
