#
# Copyright (c) 2026
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_SID_END_DEVICE_NUS_SHELL=y
CONFIG_SHELL_BT_NUS_INIT_LOG_LEVEL_NONE=y

CONFIG_BT_MAX_CONN=2
CONFIG_BT_EXT_ADV_MAX_ADV_SET=2
