CONFIG_STATE_NOTIFIER=y
CONFIG_SID_END_DEVICE_PERSISTENT_LINK_MASK=y
CONFIG_SIDEWALK_APPLICATION_NAME="hello"
CONFIG_SID_END_DEVICE_HELLO_COMPARE_AUTOSWITCH=y
CONFIG_SID_END_DEVICE_HELLO_COMPARE_FSK_DELAY_S=6
CONFIG_SID_END_DEVICE_HELLO_COMPARE_LORA_DELAY_S=12
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
